package at.fhj.cdss.rules

import arden.runtime.*;
import at.fhj.cdss.CTDSIRSNotification;
import at.fhj.cdss.CTD_SIRS_NotificationAM;
import at.fhj.cdss.CTD_SIRS_NotificationA2B;

import at.fhj.cdss.pneumonia.*;

/*
rule "temperatureAbnormalArde$n2Bytecode"
	when
	an : ArdenNumber(value==38	);
	$n2 : CTD_SIRS_NotificationA2B( $n2.getTemperature() >= an );
	
	//$n2 : CTD_SIRS_NotificationA2B( testvar >= 0 )
	then
	//$n2.setCounter(Double.parseDouble($n2.getCounter().getElements()[0])+1);
	System.out.println("AAAtemperature: "+$n2.getTemperature());
	//System.out.println("counter +1: "+$n2.getCounter().getElements()[0]);
end
*/

rule "temperature"
	when
	$n1 : CTDSIRSNotification( temperature > 38 || temperature < 36 )
	then
	$n1.setCounter($n1.getCounter()+1);
	System.out.println($n1.getCounter()+", temperature");
	update($n1);
end

rule "heartRate"
	when
	$n1 : CTDSIRSNotification( heartRate > 90 )
	then
	$n1.setCounter($n1.getCounter()+1);
	System.out.println($n1.getCounter()+", heartRate");
	update($n1);
end

rule "respRateAndPaCo2"
	when
	$n1 : CTDSIRSNotification( respRate > 20 || paCo2 < 32 )
	then
	$n1.setCounter($n1.getCounter()+1);
	System.out.println($n1.getCounter()+", respRateAndPaCo2");
	update($n1);
end


rule "wbCellCountAndimmatureBand"
	when
	$n1 : CTDSIRSNotification( wbCellCount > 12000 || wbCellCount < 4000 || immatureBand > 10 )
	then 
	$n1.setCounter($n1.getCounter()+1);
	System.out.println($n1.getCounter()+", wbCellCountAndimmatureBand");
	update($n1);
end	
	
rule "sirsNotification"
	when
	$n1 : CTDSIRSNotification( counter >= 3 )
	then 
	System.out.println("Alert for SIRS after "+$n1.getCounter()+" indications.");
end

rule "temperatureAbnormalArdenModelAM"
	when
	$n3 : CTD_SIRS_NotificationAM( $n3.getTemperature().value() >= 38 || $n3.getTemperature().value() < 36 )
	then
	$n3.setCounter($n3.getCounter().add(1));
	System.out.println($n3.getCounter()+", temperatureAbnormalAM");
	update($n3);
end

rule "heartRateAM"
	when
	$n3 : CTD_SIRS_NotificationAM( $n3.getHeartRate().value() > 90 )
	then
	$n3.setCounter($n3.getCounter().add(1));
	System.out.println($n3.getCounter()+", heartRateAM");
	update($n3);
end

rule "respRateAndPaCo2AM"
	when
	$n3 : CTD_SIRS_NotificationAM( $n3.getRespRate().value() > 20 || $n3.getPaCo2().value() < 32 )
	then
	$n3.setCounter($n3.getCounter().add(1));
	System.out.println($n3.getCounter()+", respRateAndPaCo2AM");
	update($n3);
end


rule "wbCellCountAndimmatureBandAM"
	when
	$n3 : CTD_SIRS_NotificationAM( $n3.getWbCellCount().value() > 12000 || $n3.getWbCellCount.value() < 4000 || $n3.getImmatureBand().value() > 10 )
	then 
	$n3.setCounter($n3.getCounter().add(1));
	System.out.println($n3.getCounter()+", wbCellCountAndimmatureBandAM");
	update($n3);
end
	
rule "sirsNotificationAM"
	when
	$n3 : CTD_SIRS_NotificationAM( counter.value() >= 3 )
	then 
	System.out.println("Alert for SIRS after "+$n3.getCounter()+" indications.");
end




//Pneumonia Test
rule "pnLeucocytosis"
	when
	$lcf : LeucocytosisFact( wbcount.value() > 12000)
	then
	System.out.println("pnLeucocytosis: wbcount>12000");
	$lcf.setResult(true);
	update($lcf);
end

rule "pnLeukopenia"
	when
	$lpf : LeukopeniaFact( wbcount.value() < 4000)
	then
	System.out.println("pnLeukopenia: wbcount>4000");
	$lpf.setResult(true);
	update($lpf);
end

rule "pnFever"
	when
	$btf : BodyTemperatureFact( temperature.value() > 38)
	then
	System.out.println("pnFever: temperature>38");
	$btf.setResult(true);
	update($btf);
end

rule "pnRespSymp"
	when
	$rsf : RespiratorySymptomsFact( cough.isTrue() || dyspnea.isTrue() || tachypnea.isTrue() );
	then
	System.out.println("pnRespSymp: cough or dyspnea or tachypnea");
	$rsf.setResult(true);
	update($rsf);
end

rule "pnXRay"
	when
	$xrf : XRayFact( (chestXray1.isTrue() && chestXray2.isTrue()) );
	then
	$xrf.setResult(true);
	System.out.println("XRayFact: true");
	update($xrf);
end

rule "pnPBWimberley"
	when
	$pbw : PBWimberleyFact( colonyFormingUnits.value() >= Math.pow(10,3) );
	then
	$pbw.setResult(true);
	System.out.println("PBWimberley, cfu/m3 exceed 10^3");
	update($pbw);
end

rule "pnSymptoms"
	when
	$lcf : LeucocytosisFact();//ids should be checked here
	$lpf : LeukopeniaFact();
	$btf : BodyTemperatureFact();
	$rsf : RespiratorySymptomsFact();
	$smf : SymptomsFact( $lcf.getResult.isTrue() || $lpf.getResult().isTrue() || $btf.getResult().isTrue() || $rsf.getResult().isTrue());
	then
	System.out.println("pnSymptoms: lcf: "+$lcf.getResult().toString()+"; lpf: "+ $lpf.getResult()+"; btf: "+$btf.getResult()+"; rsf: "+$rsf.getResult());
	$smf.setResult(true);
	update($smf);
	$smf.generateAction();
	System.out.println($smf.getAction().toString());
end
	
rule "Pneumonia"
	when
	$xrf : XRayFact();
	$pbw : PBWimberleyFact();
	$smf : SymptomsFact();
	$pnf : PneumoniaFact( $xrf.getResult().isTrue() || $pbw.getResult().isTrue() || $smf.getResult().isTrue() );
	then
	$pnf.setResult(true);
	update($pnf);
	System.out.println("Pneuminia true");
end